# This file is part of Hedgehog LISP.
# Copyright (C) 2003, 2004 Oliotalo Ltd.
# See file LICENSE.LGPL for pertinent licensing conditions.
#
# Author: Kenneth Oksanen <cessu@iki.fi>
#

# This file computes a checksum of the byte code mnemonics, their
# types (INSN, EXT_INSN, IMM), and relative order.  
# It MUST be executed with GNU awk.


BEGIN {
  h = 0xBADC0FFE;
  for (i = 1; i <= 127; i++)
    ord[sprintf("%c", i)] = i;
}

{
  gsub(/[ \t]/, "");
  if (/^(INSN|EXT_INSN|IMM)/) {
    n_chars = split($0, s, "");
    for (i = 1; i <= n_chars; i++) {
      h += ord[s[i]];
      h += lshift(h, 10);
      # Cut out bits possibly above the 32nd.
      h = and(h, 0xFFFFFFFF);
      h = xor(h, rshift(h, 7));
    }
  }
}

END {
  printf("/* This file is automatically generated by `hh_seed.awk' from\n");
  printf("   the contents of the `hh_insn.def' file. */\n\n");
  printf("#define HH_INSN_COOKIE  0x%08X\n", h);
}
